# -*- coding: utf-8 -*-
"""NBA_S1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_4y6GgdYcMuv8p0mFG6hguDTOBTih2rm
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

#Load Data
NBA1 = pd.read_csv('final_df1.csv', encoding= 'unicode_escape')

NBA1.head()

df = pd.DataFrame()
print (df)

#slim down the columns
NBA2 = pd.DataFrame(NBA1,columns = ['0','id','Year_pp','Rk_pp','Player_pp', 'PTS_pg', 'BLK_pg', 'STL_pg', 'AST_pg', 'TRB_pg', 'Pos_pp','Age_pp','Tm_pp','G_pp','GS_pp','MP_pp','FG_pp','FGA_pp','FG_PCT_pp'])

NBA2.head(100)

correlation = NBA2.corr()
sns.heatmap(correlation,xticklabels=correlation.PTS_pg,yticklabels=correlation.Age_pp,annot=True)

sns.relplot(x='PTS_pg',y='Age_pp',hue='Pos_pp',data=NBA2)